version: "3.8"

services:

  scraper:
    build: ../backend
    image: flask-dane-scraper:v1.0.0
 
    restart: always

    ports:
      - "5000:5000"
      - "443:443"

    environment:
      - host_mongo=mongo
      - port_mongo=27017
      - user_mongo=usuario_admin
      - password_mongo=contraseña_admin
      - API_KEY_2CAPTCHA=${API_KEY_2CAPTCHA}  
    
    networks:
      - net-dane

    hostname: flask_dane  
    
  mongo:
    image: mongo:4.4

    restart: always
    
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario_admin
      MONGO_INITDB_ROOT_PASSWORD: contraseña_admin
      MONGO_INITDB_DATABASE: scraper_data_dane

    networks:
      - net-dane

    hostname: mongo

  
        
networks:
  net-dane:
