version: "3.8"

services:

  scraper:
    image: flask-dane-scraper:v1.0.0
    
    restart: always

    ports:
      - "5000:5000"
      - "443:443"

    environment:
      - address_consul=http://consul:8500/
    
    networks:
      - net-dane

    hostname: flask_dane  
    
  mongo:
    image: mongo:4.4
    
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario_admin
      MONGO_INITDB_ROOT_PASSWORD: contraseña_admin
      MONGO_INITDB_DATABASE: scraper_data_dane

    networks:
      - net-dane

    hostname: mongo

  
        
networks:
  net-dane:
