version: "3.8"

services:

  scraper:
    image: flask-dane-scraper:v1.0.0
    
    restart: always

    ports:
      - "5000:5000"
      - "443:443"

    environment:
      - address_consul=http://consul:8500/

    networks:
      - net-matrix  
    hostname: flask-app  

  


            
networks:
  net-matrix:
